name: 天气资讯推送
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests
          python3 push.py
        env:
          SENDKEY: ${{ secrets.SENDKEY }}
