name: 天气资讯推送
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python push.py
        env:
          SENDB: ${{ secrets.SENDB }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
